import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const OutfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});



export const metadata = {
  title: "Online Book Borrowing Platform",
  description: "One of the biggest platform in Bangladesh for Borrowing Book through Online. This platform is generated by next.js This platform may helpful for all kinds of Bangladeshi students.",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar></Navbar>
        <main>
          {children}
        </main>
        <Footer></Footer>

      </body>
    </html>
  );
}
