import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Online Book Borrowing Platform",
  description: "One of the biggest platform in Bangladesh for Borrowing Book through Online. This platform is generated by next.js This platform may helpful for all kinds of Bangladeshi students.",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar></Navbar>
        <main>
          {children}
        </main>

      </body>
    </html>
  );
}
